default_language_version:
    python: python3.12
repos:
 - repo: https://github.com/pre-commit/pre-commit-hooks
   rev: v6.0.0
   hooks:
   - id: trailing-whitespace
     name: Trim Trailing Whitespace
     description: This hook trims trailing whitespaces.
     entry: trailing-whitespace-fixer
     language: python
   - id: check-json
     name: Check JSON
     description: This hook checks the syntax of JSON files.
     entry: check-json
   - id: pretty-format-json
     name: Pretty Format JSON
     description: This hook formats JSON files in a pretty way.
     entry: pretty-format-json
   - id: end-of-file-fixer
     name: End of File Fixer
     description: This hook ensures that a file ends with a newline.
     entry: end-of-file-fixer
   - id: name-tests-test
   - id: requirements-txt-fixer
   - id: check-yaml
 - repo: https://github.com/psf/black
   rev: 26.3.1
   hooks:
   - id: black
 - repo: https://github.com/pycqa/isort
   rev: 8.0.1
   hooks:
   - id: isort
     args: ["--profile", "black"]
 - repo: https://github.com/pycqa/flake8
   rev: 7.3.0
   hooks:
   - id: flake8
     args: ["--max-line-length=120", "--extend-ignore=E203, F821, E731"]
